TrajectoryPlannerROS:
  acc_lim_x: 0.4
  acc_lim_y: 0.2
  acc_lim_theta: 3.2

  
  max_vel_x: 0.3
  min_vel_x: 0.1
  max_vel_theta: 1
  min_vel_theta: -0.6

  min_in_place_vel_theta: 0.2
  sim_time: 1.7
  sim_granularity: 0.025
  angular_sim_granularity: 0.025

  path_distance_bias: 0.95
  goal_distance_bias: 0.8

  occdist_scale: 0.01
  oscillation_reset_dist: 0.05
  escape_reset_dist: 0.01
  escape_reset_theta: 1.57079632679

  vx_samples: 20
  vtheta_samples: 20

  
  escape_vel: -0.3

    
  #yaw_goal_tolerance: 0.1
  #xy_goal_tolerance: 0.3 

  controller_frequency: 10

  #dwa: true
  #heading_scoring: true

  holonomic_robot: false


#BaseGlobalPlanner:
  #orientation_mode: 4

