
footprint: [[-0.45, -0.28], [-0.45, 0.28],  [0.40, 0.28], [0.40, -0.28]]

inflation_layer:
  cost_scaling_factor: 0.7  
  inflation_radius: 0.6 #0.45

obstacle_layer:
  obstacle_range: 5
  raytrace_range: 3.0
  max_obstacle_height: 1.6 #1.3
  min_obstacle_height: 0.03
  observation_sources: scan
  scan: {data_type: LaserScan, topic: /scan_back, marking: true, clearing: true, expected_update_rate: 0, inf_is_valid: true}
  
  
#robot_radius: 0.2




