
footprint: [[-0.45, -0.28], [-0.45, 0.28],  [0.40, 0.28], [0.40, -0.28]]

inflation_layer:
  cost_scaling_factor: 0.7  
  inflation_radius: 0.2 #0.45

  #robot_radius: 0.2

obstacle_layer:
  obstacle_range: 5
  raytrace_range: 3.0
  max_obstacle_height: 1.6 #1.3
  min_obstacle_height: 0.03
  observation_sources: scan
  scan: {data_type: LaserScan, topic: /scan_gazebo, marking: true, clearing: true, expected_update_rate: 0, inf_is_valid: true}


voxel_layer:
  enabled: true
  origin_z: 0.0
  z_resolution: 0.05
  z_voxels: 10
  unknown_threshold: 0
  #mark_threshold: 2
  publish_voxel_map: true
  combination_method: 1
  observation_sources: output_points
  output_points:
    data_type: PointCloud2
    topic: /kinect/depth/points
    marking: true
    clearing: true
    obstacle_range: 1.90
    raytrace_range: 2.00
    min_obstacle_height: 0.00
    max_obstacle_height: 3.00
    mark_threshold: 3
    observation_persistence: 2.0

