local_costmap:
  global_frame: map
  robot_base_frame: chassis
  update_frequency: 1.0
  publish_frequency: 5.0
  static_map: false
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.1
  #plugins:
  #  - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
  #  - {name: voxel_layer, type: "costmap_2d::VoxelLayer"}
  #  - {name: inflation_layer,   type: "costmap_2d::InflationLayer"}
  obstacle_layer:
    obstacle_range: 5
    raytrace_range: 3.0
    max_obstacle_height: 1.6 #1.3
    min_obstacle_height: 0.03
    observation_sources: scan
    scan: {data_type: LaserScan, topic: /scan_gazebo, marking: true, clearing: true, expected_update_rate: 0, inf_is_valid: true}

  
  
 

