local_costmap:
  global_frame: map
  robot_base_frame: chassis
  update_frequency: 1.0
  publish_frequency: 5.0
  static_map: false
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.1
  #plugins:
  #  - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
  #  - {name: voxel_layer, type: "costmap_2d::VoxelLayer"}
  #  - {name: inflation_layer,   type: "costmap_2d::InflationLayer"}
 
  
  
 

