# Move base node parameters. For full documentation of the parameters in this file, please see
#
#  http://www.ros.org/wiki/move_base
#
shutdown_costmaps: true

controller_frequency: 5.0
controller_patience: 3.0

planner_frequency: 1.0
planner_patience: 5.0

#oscillation_timeout: 5.0
oscillation_distance: 0.2

track_unknown_space: true

#Recovery behavior
recovery_behaviour_enable: true
clearing_rotation_allowed: false

# local planner - default is trajectory rollout
#base_local_planner: "dwa_local_planner/DWAPlannerROS"
#base_global_planner: "global_planner/GlobalPlanner"
#base_local_planner: "eband_local_planner/EBandPlannerROS"
#base_local_planner: "teb_local_planner/TebLocalPlannerROS"